services:
  - type: web
    name: tumbi
    env: node
    plan: free
    healthCheckPath: /api/health
    buildCommand: npm install --also=dev && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - fromGroup: tumbi-secrets
